# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _swig_int
else:
    import _swig_int

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class swig_int(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    units = property(_swig_int.swig_int_units_get, _swig_int.swig_int_units_set)

    def __str__(self):
        return _swig_int.swig_int___str__(self)

    def __repr__(self):
        return _swig_int.swig_int___repr__(self)

    def __add__(self, obj1):
        return _swig_int.swig_int___add__(self, obj1)

    def __sub__(self, obj1):
        return _swig_int.swig_int___sub__(self, obj1)

    def __mul__(self, obj1):
        return _swig_int.swig_int___mul__(self, obj1)

    def __div__(self, obj1):
        return _swig_int.swig_int___div__(self, obj1)

    def __truediv__(self, obj1):
        return _swig_int.swig_int___truediv__(self, obj1)

    def __floordiv__(self, obj1):
        return _swig_int.swig_int___floordiv__(self, obj1)

    def __mod__(self, obj1):
        return _swig_int.swig_int___mod__(self, obj1)

    def __pow__(self, obj1):
        return _swig_int.swig_int___pow__(self, obj1)

    def __lshift__(self, obj1):
        return _swig_int.swig_int___lshift__(self, obj1)

    def __rshift__(self, obj1):
        return _swig_int.swig_int___rshift__(self, obj1)

    def __and__(self, obj1):
        return _swig_int.swig_int___and__(self, obj1)

    def __xor__(self, obj1):
        return _swig_int.swig_int___xor__(self, obj1)

    def __or__(self, obj1):
        return _swig_int.swig_int___or__(self, obj1)

    def __radd__(self, obj1):
        return _swig_int.swig_int___radd__(self, obj1)

    def __rsub__(self, obj1):
        return _swig_int.swig_int___rsub__(self, obj1)

    def __rmul__(self, obj1):
        return _swig_int.swig_int___rmul__(self, obj1)

    def __rdiv__(self, obj1):
        return _swig_int.swig_int___rdiv__(self, obj1)

    def __rtruediv__(self, obj1):
        return _swig_int.swig_int___rtruediv__(self, obj1)

    def __rfloordiv__(self, obj1):
        return _swig_int.swig_int___rfloordiv__(self, obj1)

    def __rmod__(self, obj1):
        return _swig_int.swig_int___rmod__(self, obj1)

    def __rpow__(self, obj1):
        return _swig_int.swig_int___rpow__(self, obj1)

    def __rlshift__(self, obj1):
        return _swig_int.swig_int___rlshift__(self, obj1)

    def __rrshift__(self, obj1):
        return _swig_int.swig_int___rrshift__(self, obj1)

    def __rand__(self, obj1):
        return _swig_int.swig_int___rand__(self, obj1)

    def __rxor__(self, obj1):
        return _swig_int.swig_int___rxor__(self, obj1)

    def __ror__(self, obj1):
        return _swig_int.swig_int___ror__(self, obj1)

    def __iadd__(self, obj1):
        return _swig_int.swig_int___iadd__(self, obj1)

    def __isub__(self, obj1):
        return _swig_int.swig_int___isub__(self, obj1)

    def __imul__(self, obj1):
        return _swig_int.swig_int___imul__(self, obj1)

    def __idiv__(self, obj1):
        return _swig_int.swig_int___idiv__(self, obj1)

    def __itruediv__(self, obj1):
        return _swig_int.swig_int___itruediv__(self, obj1)

    def __ifloordiv__(self, obj1):
        return _swig_int.swig_int___ifloordiv__(self, obj1)

    def __imod__(self, obj1):
        return _swig_int.swig_int___imod__(self, obj1)

    def __ipow__(self, obj1):
        return _swig_int.swig_int___ipow__(self, obj1)

    def __ilshift__(self, obj1):
        return _swig_int.swig_int___ilshift__(self, obj1)

    def __irshift__(self, obj1):
        return _swig_int.swig_int___irshift__(self, obj1)

    def __iand__(self, obj1):
        return _swig_int.swig_int___iand__(self, obj1)

    def __ixor__(self, obj1):
        return _swig_int.swig_int___ixor__(self, obj1)

    def __ior__(self, obj1):
        return _swig_int.swig_int___ior__(self, obj1)

    def __lt__(self, obj1):
        return _swig_int.swig_int___lt__(self, obj1)

    def __le__(self, obj1):
        return _swig_int.swig_int___le__(self, obj1)

    def __eq__(self, obj1):
        return _swig_int.swig_int___eq__(self, obj1)

    def __ne__(self, obj1):
        return _swig_int.swig_int___ne__(self, obj1)

    def __gt__(self, obj1):
        return _swig_int.swig_int___gt__(self, obj1)

    def __ge__(self, obj1):
        return _swig_int.swig_int___ge__(self, obj1)

    def __neg__(self):
        return _swig_int.swig_int___neg__(self)

    def __pos__(self):
        return _swig_int.swig_int___pos__(self)

    def __abs__(self):
        return _swig_int.swig_int___abs__(self)

    def __invert__(self):
        return _swig_int.swig_int___invert__(self)

    def __nonzero__(self):
        return _swig_int.swig_int___nonzero__(self)

    def __int__(self):
        return _swig_int.swig_int___int__(self)

    def __long__(self):
        return _swig_int.swig_int___long__(self)

    def __float__(self):
        return _swig_int.swig_int___float__(self)

    def __oct__(self):
        return _swig_int.swig_int___oct__(self)

    def __hex__(self):
        return _swig_int.swig_int___hex__(self)

    def __len__(self):
        return _swig_int.swig_int___len__(self)

    def __index__(self):
        return _swig_int.swig_int___index__(self)

    def __bool__(self):
        return _swig_int.swig_int___bool__(self)

    def __init__(self):
        _swig_int.swig_int_swiginit(self, _swig_int.new_swig_int())
    __swig_destroy__ = _swig_int.delete_swig_int

# Register swig_int in _swig_int:
_swig_int.swig_int_swigregister(swig_int)


#if SWIG_VERSION > 0x040000
def _trick_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        else:
            msg = f'You cannot add instance attribute \'{name}\' to Trick swig_int'
            raise AttributeError(msg)
    return set_instance_attr

swig_int.__setattr__ = _trick_setattr_nondynamic_instance_variable(object.__setattr__)
#endif



